// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nulls.proto

package ptypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type String struct {
	String_              string   `protobuf:"bytes,1,opt,name=String,json=string,proto3" json:"String,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=Valid,json=valid,proto3" json:"Valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ada44d2ede0c08a, []int{0}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *String) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type Bool struct {
	Bool                 bool     `protobuf:"varint,1,opt,name=Bool,json=bool,proto3" json:"Bool,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=Valid,json=valid,proto3" json:"Valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ada44d2ede0c08a, []int{1}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func (m *Bool) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type Int struct {
	Int                  int32    `protobuf:"varint,1,opt,name=Int,json=int,proto3" json:"Int,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=Valid,json=valid,proto3" json:"Valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int) Reset()         { *m = Int{} }
func (m *Int) String() string { return proto.CompactTextString(m) }
func (*Int) ProtoMessage()    {}
func (*Int) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ada44d2ede0c08a, []int{2}
}

func (m *Int) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int.Unmarshal(m, b)
}
func (m *Int) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int.Marshal(b, m, deterministic)
}
func (m *Int) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int.Merge(m, src)
}
func (m *Int) XXX_Size() int {
	return xxx_messageInfo_Int.Size(m)
}
func (m *Int) XXX_DiscardUnknown() {
	xxx_messageInfo_Int.DiscardUnknown(m)
}

var xxx_messageInfo_Int proto.InternalMessageInfo

func (m *Int) GetInt() int32 {
	if m != nil {
		return m.Int
	}
	return 0
}

func (m *Int) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type Time struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=Time,json=time,proto3" json:"Time,omitempty"`
	Valid                bool                 `protobuf:"varint,2,opt,name=Valid,json=valid,proto3" json:"Valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ada44d2ede0c08a, []int{3}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Time) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*String)(nil), "nulls.String")
	proto.RegisterType((*Bool)(nil), "nulls.Bool")
	proto.RegisterType((*Int)(nil), "nulls.Int")
	proto.RegisterType((*Time)(nil), "nulls.Time")
}

func init() { proto.RegisterFile("nulls.proto", fileDescriptor_6ada44d2ede0c08a) }

var fileDescriptor_6ada44d2ede0c08a = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x3d, 0x4b, 0x04, 0x31,
	0x14, 0x64, 0xbd, 0xdd, 0xe5, 0xcc, 0x35, 0x12, 0x44, 0x8e, 0xc5, 0xe2, 0xb8, 0xea, 0x1a, 0x13,
	0x51, 0xb0, 0xb1, 0xf2, 0x3a, 0xc1, 0x2a, 0x1e, 0x16, 0x76, 0x89, 0xc6, 0x18, 0x4c, 0xf2, 0xc2,
	0xe6, 0xad, 0xe0, 0xbf, 0x97, 0x4d, 0x5c, 0xb4, 0x58, 0xab, 0x79, 0x1f, 0x33, 0x03, 0x33, 0x64,
	0x15, 0x06, 0xe7, 0x12, 0x8b, 0x3d, 0x20, 0xd0, 0x26, 0x2f, 0xdd, 0xad, 0xb1, 0xf8, 0x3e, 0x28,
	0xf6, 0x02, 0x9e, 0x1b, 0x70, 0x32, 0x18, 0x9e, 0xff, 0x6a, 0x78, 0xe3, 0x11, 0xbf, 0xa2, 0x4e,
	0x1c, 0xad, 0xd7, 0x09, 0xa5, 0x8f, 0xbf, 0x53, 0xf1, 0xd8, 0xde, 0x90, 0xf6, 0x11, 0x7b, 0x1b,
	0x0c, 0x3d, 0x9b, 0xa6, 0x75, 0xb5, 0xa9, 0x76, 0xc7, 0xa2, 0x4d, 0xe5, 0x7e, 0x4a, 0x9a, 0x27,
	0xe9, 0xec, 0xeb, 0xfa, 0x68, 0x53, 0xed, 0x96, 0xa2, 0xf9, 0x1c, 0x97, 0xed, 0x25, 0xa9, 0xf7,
	0x00, 0x8e, 0xd2, 0x82, 0x59, 0xb3, 0x14, 0xb5, 0x1a, 0x6f, 0xf3, 0x8a, 0x0b, 0xb2, 0xb8, 0x0f,
	0x48, 0x4f, 0x32, 0x64, 0x7e, 0x23, 0x16, 0x36, 0xe0, 0x3f, 0xf4, 0x07, 0x52, 0x1f, 0xac, 0xd7,
	0x94, 0x15, 0xcc, 0x82, 0xd5, 0x55, 0xc7, 0x0c, 0x80, 0x71, 0x9a, 0x4d, 0x09, 0xd9, 0x61, 0x0a,
	0x24, 0xea, 0x31, 0xdb, 0xbc, 0xdb, 0xfe, 0xfc, 0xb9, 0xfb, 0xd3, 0xd2, 0x9d, 0xec, 0xa5, 0xb2,
	0x1f, 0xf2, 0xa7, 0x1e, 0xd5, 0x66, 0xb7, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x4a,
	0x4b, 0xc2, 0x5e, 0x01, 0x00, 0x00,
}
